HW24
OkMoroz/graduate-work-js-moroz pull request #1
Opened 2023-07-29 19:15 UTC by OkMoroz

2023-07-29 20:18 UTC, AlexDomianych requested changes

2023-07-29 20:18 UTC, AlexDomianych commented on hw-react-app/src/components/Input/index.js
> +const Input = () => {
Input має повертати не декілька <input />, а лише 1 і приймати декілька пропсів (props) які буду регулювати чи цей інпут - пароль чи ні

2023-07-29 20:18 UTC, AlexDomianych commented on hw-react-app/src/reportWebVitals.js
цей файл можна видалити

2023-07-29 20:18 UTC, AlexDomianych commented on hw-react-app/src/index.js
> +reportWebVitals();
цю строку також видалити

2023-07-30 08:16 UTC, GeFeSTTS approved these changes

2023-07-30 11:13 UTC, merged